In [3]:
import time
import os
import re
import numpy as np
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.nn.functional as F
import torchvision
from copy import deepcopy
import torchvision.transforms as transforms
from torch.utils.data.dataset import Subset
from PreResNet import ResNet18


import string
import matplotlib.pyplot as plt
from prettytable import PrettyTable
from IPython.display import Latex


# gpu or cpu
device = torch.device("cuda")

In [7]:
print("Train baseline")

table = PrettyTable([' ', 'Noise=0.3', '0.5', '0.7', '0.8', '0.9'])
for lr in [0.2, 0.1, 0.05]:
    test = [lr]
    for noise in [0.3, 0.5, 0.7, 0.8, 0.9]:
        acc = []
        for index in range(5):
            try:
                print('record/baseline_new/acc_lr_%.3f_noise_%.2f_%d.txt'%(lr, noise, index))
                file = open('record/baseline_new/acc_lr_%.3f_noise_%.2f_%d.txt'%(lr, noise, index))               
                lines = file.readlines()
                test_acc = []
                for line in lines:
                    new_line = re.split(':|,| |\n', line.strip())
                    test_acc.append(eval(new_line[12]))
                acc.append(max(test_acc))
                print(acc)
            except:
                pass
        if len(acc)>0:
            test.append(str(np.round(np.mean(acc),3)) + '(' + str(len(acc)) + ')')
        else:
            test.append('/')
    table.add_row(test)
print(table)



Train baseline
record/baseline_new/acc_lr_0.200_noise_0.30_0.txt
record/baseline_new/acc_lr_0.200_noise_0.30_1.txt
record/baseline_new/acc_lr_0.200_noise_0.30_2.txt
record/baseline_new/acc_lr_0.200_noise_0.30_3.txt
record/baseline_new/acc_lr_0.200_noise_0.30_4.txt
record/baseline_new/acc_lr_0.200_noise_0.50_0.txt
record/baseline_new/acc_lr_0.200_noise_0.50_1.txt
record/baseline_new/acc_lr_0.200_noise_0.50_2.txt
record/baseline_new/acc_lr_0.200_noise_0.50_3.txt
record/baseline_new/acc_lr_0.200_noise_0.50_4.txt
record/baseline_new/acc_lr_0.200_noise_0.70_0.txt
record/baseline_new/acc_lr_0.200_noise_0.70_1.txt
record/baseline_new/acc_lr_0.200_noise_0.70_2.txt
record/baseline_new/acc_lr_0.200_noise_0.70_3.txt
record/baseline_new/acc_lr_0.200_noise_0.70_4.txt
record/baseline_new/acc_lr_0.200_noise_0.80_0.txt
record/baseline_new/acc_lr_0.200_noise_0.80_1.txt
record/baseline_new/acc_lr_0.200_noise_0.80_2.txt
record/baseline_new/acc_lr_0.200_noise_0.80_3.txt
record/baseline_new/acc_lr_0.200_no

In [7]:
print(sum([[i]*2 for i in range(10)], []))

[0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9]


In [12]:
a = [1,2,3]
print(a/np.sum(a))

[0.16666667 0.33333333 0.5       ]


In [19]:
y = np.array([0]*5+[1]*5+[2]*5)
print(y)
index_list = []
for i in range(3):
    indices = np.where(y==i)[0]
    index_list.append(indices)
    print(indices)
print(index_list)

[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]
[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
